license: "6Gi59MRUebBFf68wIB"

storage:
  # Options: MySQL or MongoDB (Is not yet supported)
  # Set the login of these either under here
  type: MySQL

  auth:
    host: localhost
    port: 3306
    database: minetopia
    username: root
    password: ''

  redis:
    address: "127.0.0.1"
    port: 6379
    password: ""

discord:
  token: ""
  command-logs: 736639994760003594